name: sip_flutter
description: A SIP Flutter project.

version: 1.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.6
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.catelt.sip_flutter
        pluginClass: SipFlutterPlugin
      ios:
        pluginClass: SipFlutterPlugin
